# **02 - Exploratory Data Analysis (EDA)**
---

## **Table of Content**
[Objective](#obj)

[Dataset Info](#data-info)

[Summary](#summary)

## <a id ='obj'></a>**Objective**
To uncover temporal patterns, seasonalities and feature correlations to inform effective feature engineering, data preprocessing, and model architecture selection for accurate time series forecasting.

## <a id ='data-info'></a> **Dataset Info**
* **Source:** UCI Machine Learning Repository
* **Title:** Appliances Energy Prediction
* **Time Range:** 11th January 2016 - 27th May 2016
* **Primary Target Variable:** `Appliances` (Watt-hour consumed)

## <a id = 'summary'></a>**Summary**

## **Import Necessary Libraries**

In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from src.preprocess import preprocess_energy
from pathlib import Path

## **Import Raw Dataset**

In [24]:
PROJECT_ROOT = Path.cwd().parent

# Import csv file
energy = pd.read_csv(f'{PROJECT_ROOT}/data/raw/energydata_complete.csv')

In [25]:
# Print samples
energy.head(3)

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668

# **Preprocess Using Method**

In [26]:
# Call preprocess_energy method
energy = preprocess_energy(energy)

# Print preprocessed samples
energy.head(3)

Preprocessing completed.

,Appliances,lights,rv1,rv2,T_indoor,RH_indoor,T_liv_room,RH_liv_room,T_bathroom,RH_bathroom,T_outdoor,RH_outdoor
date,,,,,,,,,,,,
2016-01-11 17:00:00,60,30,13.275433,13.275433,18.518889,45.658333,19.2,44.790000,17.166667,55.20,7.026667,84.256667
2016-01-11 17:10:00,60,30,18.606195,18.606195,18.524444,45.576528,19.2,44.722500,17.166667,55.20,6.833333,84.063333
2016-01-11 17:20:00,50,30,28.642668,28.642668,18.501111,45.464444,19.2,44.626667,17.166667,55.09,6.560000,83.156667

## **Initial Inspection**

We'll first inspect the dataset characteristics, such as the shape, data types and so on.

In [29]:
print(f'Number of Rows: {energy.shape[0]}')
print(f'Number of Columns: {energy.shape[1]}')

print('\n\n---DATASET INFORMATION---')
print(energy.info())

Number of Rows: 19735
Number of Columns: 12


---DATASET INFORMATION---
<class 'pandas.DataFrame'>
DatetimeIndex: 19735 entries, 2016-01-11 17:00:00 to 2016-05-27 18:00:00
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Appliances   19735 non-null  int64
 1   lights       19735 non-null  int64
 2   rv1          19735 non-null  float64
 3   rv2          19735 non-null  float64
 4   T_indoor     19735 non-null  float64
 5   RH_indoor    19735 non-null  float64
 6   T_liv_room   19735 non-null  float64
 7   RH_liv_room  19735 non-null  float64
 8   T_bathroom   19735 non-null  float64
 9   RH_bathroom  19735 non-null  float64
 10  T_outdoor    19735 non-null  float64
 11  RH_outdoor   19735 non-null  float64
dtypes: float64(10), int64(2)
memory usage: 2.0 MB
None