# **02 - Exploratory Data Analysis (EDA)**
---

## **Table of Content**
[Objective](#obj)

[Dataset Info](#data-info)

[Summary](#summary)

## <a id ='obj'></a>**Objective**
To uncover temporal patterns, seasonalities and feature correlations to inform effective feature engineering, data preprocessing, and model architecture selection for accurate time series forecasting.

## <a id ='data-info'></a> **Dataset Info**
* **Source:** UCI Machine Learning Repository
* **Title:** Appliances Energy Prediction
* **Time Range:** 11th January 2016 - 27th May 2016
* **Primary Target Variable:** `Appliances` (Watt-hour consumed)

## **Domain-Related Questions**
In this section, we'll define the set of questions we'd like to answer from this EDA.

> **Q1**: What are the dominant daily and weekly consumption cycles, and does downsampling from 10-minute intervals to 30-minute or 1-hour steps preserve key signals while reducing noise?

> **Q2**: Do energy habits stay the same from January to May, or does the changing season (winter to spring) shift baseline power usage?

> **Q3**: How strongly does the current electrical consumption depends on past information, and how dae back does the influence persist?

> **Q4**: Which environmental variables correlate most strongly with appliance energy usage, and are these relationships immediate or lagged?

> **Q5**: What influences wild fluctuation in appliances electrical usage, and does log transformation stabilize the variance?

## <a id = 'summary'></a>**Summary**

## **Import Necessary Libraries**

In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from src.preprocess import preprocess_energy
from pathlib import Path

## **Import Raw Dataset**

In [24]:
PROJECT_ROOT = Path.cwd().parent

# Import csv file
energy = pd.read_csv(f'{PROJECT_ROOT}/data/raw/energydata_complete.csv')

In [25]:
# Print samples
energy.head(3)

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668

# **Preprocess Using Method**

In [26]:
# Call preprocess_energy method
energy = preprocess_energy(energy)

# Print preprocessed samples
energy.head(3)

Preprocessing completed.

,Appliances,lights,rv1,rv2,T_indoor,RH_indoor,T_liv_room,RH_liv_room,T_bathroom,RH_bathroom,T_outdoor,RH_outdoor
date,,,,,,,,,,,,
2016-01-11 17:00:00,60,30,13.275433,13.275433,18.518889,45.658333,19.2,44.790000,17.166667,55.20,7.026667,84.256667
2016-01-11 17:10:00,60,30,18.606195,18.606195,18.524444,45.576528,19.2,44.722500,17.166667,55.20,6.833333,84.063333
2016-01-11 17:20:00,50,30,28.642668,28.642668,18.501111,45.464444,19.2,44.626667,17.166667,55.09,6.560000,83.156667

## **Initial Inspection**

We'll first inspect the dataset characteristics, such as the shape, data types and so on.

In [29]:
print(f'Number of Rows: {energy.shape[0]}')
print(f'Number of Columns: {energy.shape[1]}')

print('\n\n---DATASET INFORMATION---')
print(energy.info())

Number of Rows: 19735
Number of Columns: 12


---DATASET INFORMATION---
<class 'pandas.DataFrame'>
DatetimeIndex: 19735 entries, 2016-01-11 17:00:00 to 2016-05-27 18:00:00
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Appliances   19735 non-null  int64
 1   lights       19735 non-null  int64
 2   rv1          19735 non-null  float64
 3   rv2          19735 non-null  float64
 4   T_indoor     19735 non-null  float64
 5   RH_indoor    19735 non-null  float64
 6   T_liv_room   19735 non-null  float64
 7   RH_liv_room  19735 non-null  float64
 8   T_bathroom   19735 non-null  float64
 9   RH_bathroom  19735 non-null  float64
 10  T_outdoor    19735 non-null  float64
 11  RH_outdoor   19735 non-null  float64
dtypes: float64(10), int64(2)
memory usage: 2.0 MB
None

In [31]:
# Print statistics overview
energy.describe()

,Appliances,lights,rv1,rv2,T_indoor,RH_indoor,T_liv_room,RH_liv_room,T_bathroom,RH_bathroom,T_outdoor,RH_outdoor
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,3.801875,24.988033,24.988033,21.098593,39.734318,20.341219,40.420420,19.592106,50.949283,7.910939,54.609083
std,102.524891,7.935988,14.496634,14.496634,1.841413,4.049658,2.192974,4.069813,1.844623,9.022034,6.090347,31.149806
min,10.000000,0.000000,0.005322,0.005322,16.085278,30.437333,16.100000,20.463333,15.330000,29.815000,-6.065000,1.000000
25%,50.000000,0.000000,12.497889,12.497889,19.939722,36.635214,18.790000,37.900000,18.277500,45.400000,3.626667,30.025000
50%,60.000000,0.000000,24.897653,24.897653,20.902778,39.028333,20.000000,40.500000,19.390000,49.090000,7.300000,55.290000
75%,100.000000,0.000000,37.583769,37.583769,22.127901,42.687685,21.500000,43.260000,20.619643,53.663333,11.256000,83.226667
max,1080.000000,70.000000,49.996530,49.996530,26.125000,50.921204,29.856667,56.026667,25.795000,96.321667,28.290000,99.900000

## **Question-Driven Analysis**

Every question in this section follows a standardized 4-step structure:

1. **Question**: The target question being investigated.

2. **Hypothesis**: Anticipated finding based on domain context or prior logic.

3. **Analysis**: Iterative plots paired directly with analytical notes.

4. **Summary and Takeaways**: Key insights translated into concrete feature engineering decision points.

<br>

---

> ### **Q1**: *What are the dominant daily and weekly consumption cycles, and does downsampling from 10-minute intervals to 30-minute or 1-hour steps preserve key signals while reducing noise?*

#### **Hypothesis**
Daily consumption will **peak during daytime/evening hours** and **drop overnight** during sleep, with **higher overall volume on weekends** due to home occupancy. Downsampling to 30-minute/1-hour steps  will **smooth out sensor noise** while **preserving the core peaks and fluctuations** required for modelling.

#### **Analysis**

---
> ### **Q2**: *Do energy habits stay the same from January to May, or does the changing season (winter to spring) shift baseline power usage?*

---
> ### **Q3**: *How strongly does the current electrical consumption depends on past information, and how dae back does the influence persist?*

---
> ### **Q4**: *Which environmental variables correlate most strongly with appliance energy usage, and are these relationships immediate or lagged?*

---
> ### **Q5**: *What influences wild fluctuation in appliances electrical usage, and does log transformation stabilize the variance?*